### ISSUE TITLE
Problems with code running results that don't match the paper

### ISSUE THREAD

**Issue by Kqingzheng** [ILikeCode0/Dup-Hunter#1]
Hello Author:
I tried to run the code following the steps in the readme.md file, and when I run the command "python run.py -r True -f remove_9 -m 0 -i 14" to get the results of the experiment, the results are very different from the results in the paper, and I tried to change the parameter modelname to I tried to change the parameter modelname to "5, 80, 90, 95" but still can't get similar results as in the paper, how can I solve this?
[result.txt](https://github.com/ILikeCode0/Dup-Hunter/files/13324457/result.txt)
![微信图片_20231111123601](https://github.com/ILikeCode0/Dup-Hunter/assets/49307342/1f9d195d-8e51-4345-80d4-3baf7a772dbc)
![Uploading 微信图片_20231111123759.png…]()

**Comment by ILikeCode0** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ILikeCode0** [comment]
Thank you for your contribution! 

Note, there's a large file "data/train-dataset/first_nondup_pull_info_X.txt". 
Make sure you have cloned this file.

**Comment by Kqingzheng** [comment]
Thank you for your prompt reply!
I have made sure that this file is in my folder
![微信图片_20231111132536](https://github.com/ILikeCode0/Dup-Hunter/assets/49307342/931d8957-fa81-4d47-a752-ee69da6188a8)

**Comment by ILikeCode0** [comment]
Then, actually, i can reproduce this result with no trained model used for testing.
You can try the following steps:
1. You may change the load path in line 253 in getResult.py?
2.If you truly restore a checkpoint model, there will be a "yes" printed on the terminal.

**Comment by Kqingzheng** [comment]
Thank you!
I have gotten my desired results.
Thank you again for your excellent work on this paper！
